compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

# NOTE: If you see packages not being hoisted, its probably caused by a version mismatch between different packages or the root.
nmHoistingLimits: none